### PR TITLE
Issue/199/bulk emails

### PR DESCRIPTION
**Pull request by joshglazer**
# Description

Enhance the bulk-email functionality
 - Only show facility types that are present in the system
 - Send the correct parameters to the API for facility type
 - Add a checkbox to be able to select one or more facilities and bulk email all selected facilities
 - fix bugs related to the button that shows that allows a user to email a specific facility
 - add an edit button to the facility's action table cell

## Related PRs

List related PRs against other branches:

| branch          | PR       |
| --------------- | -------- |
| other_pr_description | # |

## Related Issues

List related Issues:

| link |
| ---- |
|  #  |

## Todos

- [ ] Tests
- [ ] Documentation

## Deploy Notes

Notes regarding deployment the contained body of work. 

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```sh
commands to test PR
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

-

### CODE REVIEW

**Comment by blakenan-bellese** [comment]
@joshglazer I played with this a bit and have one request...  Can we change the behavior of the system when the button "Email Selected Facilities" is clicked?  Instead of displaying the same "Send Email to Facilities" dialog that is show when clicking the "Email Facilities" button, I'm thinking we just show some sort of confirmation.  Something like "Please confirm you want to send an email to contacts of ## selected facilities".   I know the filters (selected ID + Type) will be accepted together by the backend, but that is an unlikely use case for the front end and I'm concerned it'll cause confusion.

**Comment by joshglazer** [comment]
@blakenan-bellese I pushed some code last week that includes a fix that's similar to what you suggested. Let me know what you think.

**Comment by blakenan-bellese** [comment]
@joshglazer I tested this with PR320 on the back end and it looks good.  It functions as expected.  I have some feedback for mostly on toast messages modals.  Here's my feedback:
1) The toast message is a bit inaccurate with using the "Email Facilities" button.  The message says "Success: Emails sent to XX facilities" where XX is NOT the number of facilities being sent emails.  Instead XX is actually the number of emails sent which is also equal to the number of contacts to which emails were sent.   Ideally this would say "Success: Emails sent to YY contacts at XX facilities".  If this is not easy/feasible, then changing the message to say "Success: XX emails sent (1 email per contact per facility)" 
2) One enhancement (can be captured as new issue) on the toast message.  If a user sends email to facility without any contacts then the toast message is something like "Error - Mail failed to send". 
3)  The "Send Email to Facilities" conformation includes the text "Are you sure you want to send an email to the following facilities?".  Can we revise this to "Are you sure you want to send an email to the contacts of the following facilities?"  to reinforce the contact>facility relationship.

**Comment by joshglazer** [comment]
@blakenan-bellese those are all great ideas, I've taken care of all of them, and sent in a small change to PR320 to handle your first request.

When I click the email icon on an entity that does not have any contacts, I'm already seeing an error message.  Is there a different way to reproduce the issue that you are referring to in your second request?

**Review by blakenan-bellese — APPROVED** [review]

**Pull request merged**
