### PR TITLE
Created component for Vacc form

### PR DESCRIPTION
**Pull request by blakenan-bellese**
# Description

Created new Vaccination form that replaces existing Covid Form.  

## Related PRs

None

## Related Issues

Resolves issue #250 

List related Issues:

| link |
| ---- |
|  #250 |

### CODE REVIEW

**Comment by blakenan-bellese** [comment]
@revjtanton I submitted this PR as draft because I wanted to get your feedback on the code change in Factility.vue that I made to get this new questionnaire to display.  Seemed inelegant to me...

**Comment by blakenan-bellese** [comment]
The form is now ready for use based on feedback from city health department, removing draft label.

**Review by funkybunch — APPROVED** [review]
Code looks good! @blakenan-bellese this is intended to replace the existing form, correct?

**Comment by blakenan-bellese** [comment]
@funkybunch Yup, replace the existing form.

**Pull request merged**
