### PR TITLE
heroku deploy from dockerfile successful

### PR DESCRIPTION
**Pull request by jbixon13**
# Description

Dockerfile added to containerize and prep for CI/CD pipeline

## Related PRs

List related PRs against other branches:

| branch          | PR       |
| --------------- | -------- |
| other_pr_description | # |

## Related Issues

List related Issues:

| link |
| ---- |
|  #20 |
|  #23 |

## Todos

- [ ] Tests
- [ ] Documentation

## Deploy Notes

Notes regarding deployment the contained body of work. 

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```sh
./start.sh
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

- development
- CI/CD

### CODE REVIEW

**Comment by jbixon13** [comment]
@revjtanton ready for re-review

**Comment by revjtanton** [comment]
Screenshot of error 
image

**Comment by jbixon13** [comment]
I can change app to backend and update the readme. It's running on my machine; I'll take another look at it later today I think I know what's going wrong. 

What if you run `npm install` in the frontend dir first and then run `docker-compose up`?

**Comment by jbixon13** [comment]
@revjtanton some updates: the issue was being caused by not running `npm install` prior to running `docker-compose up`, so there was no local `node_modules` folder to pull into the docker image.

I've updated the `README` to reflect the additional steps needed prior to running `docker-compose up`, but the better solution (in my mind) would be a `bash` script that checks for `node_modules` in the `backend` and `frontend` folders and runs `npm install` if needed, then `docker-compose up`. 

I've added a start.sh bash script that aims to accomplish this, but I'm not that familiar with bash scripting so the logic is set up properly but it does not run npm install correctly if needed. Not sure if this is a problem with bash scripting or npm because it runs correctly (says it has installed, etc.) but `node_modules` is not added as expected. I'll play around with it a little more but feel free to take a look if you have any experience with bash scripting / automating npm

**Comment by jbixon13** [comment]
nevermind, there was a logic issue in the bash script. Fixed and updated README accoringly.

**Comment by revjtanton** [comment]
I'm going to squeeze in some of this github cleanup so we can get the travis checks in place with this PR too.

**Pull request merged**
